---
# dist: trusty
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - libusb-1.0-0:i386
    - libusb-1.0-0-dev
    - libudev-dev

#compiler:
#  - clang
#  - gcc
#
#

script:
    - cd commandline
    - make
    - make blink1-tiny-server
    - make package

    
