os: unstable
#environment:
##

platform:
#- x86
- x64

install:
- ps: $env:Path += ";C:\MinGW\bin";

build_script:
- ps: cd commandline
- ps: make
- ps: make package

artifacts:
    - path: 'commandline\blink1-tool*.zip'
      name: blink1-tool
    - path: 'commandline\blink1-lib*.zip'
      name: blink1-lib
