os: unstable
environment:
#  NODE_PRE_GYP_GITHUB_TOKEN:
#    secure: VYJPed/ilAHFpd7S0zW/C2U1jVqayW5QFBitwBqralJlKlgAPW6n1L1VUIOJswiW

platform:
#- x86
- x64

install:
- ps: cd commandline
- ps: make
- ps: make libusb
- ps: make package
